/// GENERATED by POC_notes/generate_sez_s2.py; Research main ed9122b3d5ac11442714ecaef4cc4316c4706342.
/// Constants read from data/rom-cache/sez/surface-runtime-contracts.json (mirrored byte for byte); block ids and timings only, no authored behaviour.
function chaos_sez_s2_contract() {
    if (variable_global_exists("chaosSezS2Contract")) return global.chaosSezS2Contract;
    global.chaosSezS2Contract = {crumble:{block:175,replacement_block:176,surface:12,object_type:19,parent_slots:[0,16],child_slots:[7,18],hold_updates:16,break_offset:17,children_offset:18,hold_anchor_offset:-40,object_dx:14,object_dy:24,shard_parameters:[3,8,5,1],shard_dx:[-14,-6,2,10],shard_dy:-24,shard_first_move:[22,27,24,20],sound_request:163,handler_states:[0,1,2,3,4,5,6,7,8,9,10,11,14,15,16,17,18,20,21,25,26,27,28,29,30,33,34]},booster:{block:167,surface:26,x_speed:1792,max_x_speed:1792,requested_state:16,sound_request:189,ring_probe_states:[0,1,2,3,4,5,6,7,8,9,10,11,14,15,16,17,18,20,21,23,25,26,27,28,29,30],effect5:{tile:344,period_calls:6,first_image:1,second_image:2,first_image_source_file:478717,second_image_source_file:478685}},research:"ed9122b3d5ac11442714ecaef4cc4316c4706342"};
    return global.chaosSezS2Contract;
}
