// Audit capture only: actual shipped GML; see summary.evidence for host limits.
const fs=require('fs'),path=require('path'),assert=require('assert');const {lab,out}=require('./audit_player_state_adapter');
const save=(n,rows)=>fs.writeFileSync(path.join(out,n+'.jsonl'),rows.map(r=>JSON.stringify(r)).join('\n')+'\n');
const seed={x:496,y:334,vx:0,state:5,move:0,bg:2};
const good=lab('aqz3').run(seed,500,()=>({right:true}));
const bad=lab('aqz3').run(seed,500,t=>t>=20&&t<24?{left:true}:{right:true});
save('aqz3-success',good.rows);save('aqz3-failure',bad.rows);
// THZ1 has room instances rather than generated rows: instantiate the room's actual weak spring.
const weakLab=lab('thz1');const room=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../rooms/ROM_chaos_thz1/ROM_chaos_thz1.yy')));
const find=(o)=>{if(!o||typeof o!=='object')return null;if(o.objectId?.name==='OBJ_chaos_object_spring_26_weak')return o;for(const v of Object.values(o)){const r=find(v);if(r)return r;}return null;};
const obj=find(room);assert(obj);assert.equal(obj.x,1912);assert.equal(obj.y,864);
const weak=weakLab.run({x:1912,y:846,vx:0,state:5,move:0,bg:2},120,()=>({}),({h,c})=>h.create(c.OBJ_chaos_object_spring_26_weak,obj.x,obj.y));save('weak26',weak.rows);
const transitions=r=>r.rows.filter((t,i)=>!i||t.after.state!==r.rows[i-1].after.state||t.after.next!==r.rows[i-1].after.next||t.sprite!==r.rows[i-1].sprite).map(t=>({update:t.update,...t.after,sprite:t.sprite,index_model:t.image_index_model,speed:t.image_speed,playerJump:t.playerJump,playerJumpSpring:t.playerJumpSpring}));
const launches=r=>r.rows.flatMap(t=>t.events.filter(e=>e.call.includes('spring')&&JSON.stringify(e.before)!==JSON.stringify(e.after)).map(e=>({update:t.update,...e})));
const bosses=[];for(const d448 of [0,255]){const l=lab('thz3'),{h,c,g}=l;const b=c.chaos_boss_new();const p=l.player(c.chaos_boss_x(b),b.y-48,{state:10,move:3,vy:256,bg:0});p.chaosCore.d448=d448;c.SCR_chaos_core_publish(p);c.SCR_chaos_core_sprites(p);const before=l.snap(p.chaosCore);const result=c.chaos_boss_contact(b,p.chaosCore,true);c.SCR_chaos_core_publish(p);assert.equal(result,2);const contact={before,result,after:l.snap(p.chaosCore),sprite:p.sprite_index,playerJump:g.playerJump,playerJumpSpring:g.playerJumpSpring};const rows=[];for(let t=0;t<100;t++){h.frame({});rows.push({update:t,after:l.snap(p.chaosCore),sprite:p.sprite_index,image_index_model:p.image_index,image_speed:p.image_speed,playerJump:g.playerJump,playerJumpSpring:g.playerJumpSpring});p.image_index=(p.image_index+p.image_speed)%2;}save('thz3-bounce-d448-'+d448,rows);bosses.push({d448,contact,transitions:transitions({rows})});}
const different=(f)=>good.rows.findIndex((r,i)=>JSON.stringify(f(r))!==JSON.stringify(f(bad.rows[i])));
const summary={evidence:'Shipped GML in deterministic host. Camera follows player; scene/audio/GM mask mocked. image_index_model approximates engine advancement and is NOT native frame evidence or a ROM oracle. Update numbers start at zero. Controlled input variations are not a recorded Windows playthrough.',seed,success:{end:good.end,launches:launches(good),breaks:good.rows.filter(t=>t.broken.length).map(t=>({update:t.update,cells:t.broken})),transitions:transitions(good)},failure:{end:bad.end,launches:launches(bad),transitions:transitions(bad)},firstNumericDivergence:different(t=>t.after),firstStateDivergence:different(t=>[t.after.state,t.after.next,t.after.d503]),weak:{object:{x:obj.x,y:obj.y,resource:obj.objectId.name},end:weak.end,launches:launches(weak),transitions:transitions(weak)},bosses};fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify(summary,null,2));
assert(summary.success.end.x>1700);assert(summary.failure.end.x<810);assert.equal(summary.firstStateDivergence,44);assert(launches(weak).some(e=>e.after.next===11&&e.after.vy===-5&&e.after.d448===0));
console.log(JSON.stringify({success:good.end,failure:bad.end,firstStateDivergence:summary.firstStateDivergence,weak:summary.weak.transitions,bossTransitions:bosses[0].transitions},null,2));

// Canonical horizontal-block probes: same terrain and inputs, three initial core states.
const horizontal=[];for(const state of [9,14,28])for(const y of [210,218,226,234,242,250]){const l=lab('aqz3'),r=l.run({x:1030,y,vx:-1024,vy:0,state,move:3,bg:0},12,()=>({left:true}));const calls=r.rows.flatMap(t=>t.events.filter(e=>e.call==='SCR_cc_spring'&&Math.abs(e.args[0])===1).map(e=>({update:t.update,spring:e,after:t.after,sprite:t.sprite})));if(calls.length)horizontal.push({state,y,calls});}fs.writeFileSync(path.join(out,'horizontal-probes.json'),JSON.stringify(horizontal,null,2));
