// Old-POC replay: runs the platform / spike oracle battery against the ACCEPTED checkpoint 7799c34 (read from git, never from the working tree) and writes the
// result as a table. Run before the replacement landed; kept so the mismatch list stays reproducible.
// Usage: node verification/replay_legacy_platform_spike.js [ref=7799c34] [--from-json results.json]   -> docs/platform-spike-replay.md
const fs = require('fs'), path = require('path'), cp = require('child_process');
const root = path.resolve(__dirname, '..');
const args = process.argv.slice(2), ref = args.find(a => !a.startsWith('--') && !a.endsWith('.json')) || '7799c34';
const jsonArg = args.indexOf('--from-json') >= 0 ? args[args.indexOf('--from-json') + 1] : null;
let data;
if (jsonArg) data = JSON.parse(fs.readFileSync(jsonArg, 'utf8'));
else {
    const tmp = path.join(require('os').tmpdir(), `replay_${Date.now()}.json`);
    cp.spawnSync('node', [path.join(__dirname, 'run_battery.js'), ref], {cwd: root, env: Object.assign({}, process.env, {BATTERY_JSON: tmp}), stdio: 'ignore', maxBuffer: 1 << 28});
    data = JSON.parse(fs.readFileSync(tmp, 'utf8'));
}
const esc = s => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
const lines = [`# Old POC replay (${data.ref}) against the Research platform / spike fixtures`, '',
    `Generated by \`verification/replay_legacy_platform_spike.js\`. The shipped GML of the accepted checkpoint is executed through its real adapter by \`verification/chaos_world_harness.js\`; expectations are the Research cache rows (\`POC_notes/rom-cache/platform-spike-collision.json\`).`, '',
    `**${data.passed} / ${data.total} checks pass on the old POC.** Failures are listed with the measured detail.`, '', '| id | area | check | old POC | detail |', '|---|---|---|---|---|'];
for (const r of data.results) lines.push(`| ${r.id} | ${r.area} | ${esc(r.desc)} | ${r.pass ? 'pass' : '**MISMATCH**'} | ${r.pass ? '' : esc(String(r.detail).slice(0, 300))} |`);
fs.writeFileSync(path.join(root, 'docs/platform-spike-replay.md'), lines.join('\n') + '\n');
console.log(`${data.ref}: ${data.passed}/${data.total} pass -> docs/platform-spike-replay.md`);
