const fs=require('fs'),assert=require('assert'),{loadHost,root}=require('./chaos_world_harness');
const D=require('../POC_notes/rom-cache/aqz/boss-59-runtime.json'),h=loadHost(),c=h.ctx,g=h.g;let checks=0;
function eq(a,b,m){assert.deepStrictEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)),m);checks++;}
function setup(type=89){let b=c.chaos_59_new(),pool={slots:Array.from({length:19},()=>c.chaos_s2_slot())},s=c.chaos_59_slot(type,0,1856,160,0),k=c.SCR_cc_new(1956,160),vp=c.chaos_vp_new(1727,78,256,192);Object.assign(s,{state:9,requested:9,frame:2,ex:20,ey:64,hp:10,counter:255,keep:true});k.state=5;k.next=5;pool.slots[7]=s;g.powerInv=false;return {b,pool,s,k,vp};}
function cmp(s,e,label){for(let [a,b]of Object.entries({type:'type',state:'state',requested:'request',frame:'frame',timer:'duration',vx:'vx',vy:'vy',angle:'angle',saved_request:'saved_request',counter:'counter30',cooldown:'cooldown31',field23:'field23',field24:'field24',hp:'hp',field34:'field34',field35:'field35',field38:'field38',parameter:'parameter'}))eq(s[a],e[b],label+' '+a);eq([c.chaos_59_x(s),c.chaos_59_y(s),s.xu&255,s.yu&255],[e.x,e.y,...e.fractions],label+' position');}
for(let [dx,dy,req]of D.boundaries.trigger){let {s,k}=setup();s.yu=238*256;k.xu=(1856+dx)*256;k.yu=(238+dy)*256;eq(c.chaos_59_trigger(s,k),req===2,'strict trigger');}
for(let v of D.boundaries.cached_screen){let {b,pool,s,k,vp}=setup();s.vx=v.vx;s.vy=-1536;s.sx=v.cached_x;c.chaos_59_callback(b,pool,s,0xAA6C,k,true,vp);cmp(s,v.result,'cached X');}
for(let v of D.boundaries['5c_parameters']){let {b,pool,s,k,vp}=setup(92);s.state=2;s.requested=2;s.frame=0;s.parameter=v.parameter;pool.slots[7]=c.chaos_59_slot(89,0,1856,160,0);pool.slots[7].field23=255;c.chaos_59_callback(b,pool,s,0xADBE,k,true,vp);cmp(s,v.result,'5C parameter '+v.parameter);}
for(let hp=0;hp<D.boundaries.hp.length;hp++){let {b,pool,s,k,vp}=setup();s.hp=hp;k.xu=1856*256;k.yu=96*256;k.move=2;c.chaos_59_combat_contact(b,s,k,true,vp);cmp(s,D.boundaries.hp[hp],'HP '+hp);}
for(let v of D.contacts.posture){let {b,pool,s,k,vp}=setup();s.hp=v.hp;s.cooldown=v.cooldown;k.xu=(1856+v.point[0])*256;k.yu=(160+v.point[1])*256;k.move=v.attack|v.hurt|v.blink;k.vx=384;k.vy=256;g.powerInv=v.power===6;c.chaos_59_combat_contact(b,s,k,true,vp);cmp(s,v.result,'posture');eq([k.xu/256,k.yu/256,k.vx,k.vy,k.next],[v.result.player.x,v.result.player.y,v.result.player.vx,v.result.player.vy,v.result.player.requested],'player response');}
for(let [angle,vx,vy]of D.children.angular_velocity){let {s}=setup(92);s.angle=angle;s.saved_request=128;c.chaos_59_velocity(s);eq([s.vx,s.vy],[vx,vy],'angle '+angle);}
for(let v of D.children.contact_sleep_vectors){let {b,pool,s,k,vp}=setup(v.type);pool.slots[7]=c.chaos_59_slot(89,0,1856,160,0);s.state=1;s.requested=1;s.frame=v.type===90?28:v.type===91?11:v.type===93?24:v.callback===0xADAE?14:16;c.chaos_59_load_frame(s);s.saved_request=128;s.cooldown=4;s.vx=-128;s.vy=-512;s.asleep=!!v.sleep;k.xu=(1856+v.point[0])*256;k.yu=(160+v.point[1])*256;k.move=v.attack|v.hurt|v.blink;g.powerInv=v.power===6;c.chaos_59_callback(b,pool,s,v.callback,k,true,vp);cmp(s,v.result,'child '+v.type+'/'+v.callback);eq(k.stage_request,v.result.player.damage===255?255:0,'forced hurt');}
for(let v of D.script_spawns.success){let {b,pool,s,k,vp}=setup();s.state=0;s.requested=v.state;s.frame=0;s.counter=6;let n={5:6,6:400,10:16,11:6,13:3,14:20}[v.state],events=[];for(let u=1;u<=n;u++){b.tick=u;c.chaos_59_script(b,pool,s,k,true,vp);}events=b.spawns.map(e=>[e[0],e[1],e[2],e[3],e[4],0xD540+64*e[5]]);eq(events,v.events.map(e=>[e.u,e.type,e.parameter,e.x,e.y,e.slot]),'script spawns '+v.state);cmp(s,v.result,'script '+v.state);}
for(let v of D.script_spawns.partial_failure){let {b,pool,s,k,vp}=setup();s.state=0;s.requested=14;s.frame=0;for(let i=8;i<18;i++)pool.slots[i].type=255;for(let i=0;i<v.free_slots;i++)pool.slots[8+i].type=0;for(let u=0;u<20;u++)c.chaos_59_script(b,pool,s,k,true,vp);eq(b.spawns.map(e=>e[2]),v.parameters,'allocator exhaustion');}
for(let v of D.camera_clear.hud_allocator){let {b,pool,s}=setup();for(let i=0;i<16;i++)pool.slots[i].type=255;if(v.free_index!==null)pool.slots[v.free_index].type=0;c.chaos_59_hud_alloc(b,pool,s);eq(s.field34+256*s.field35,v.stored_pointer,'HUD pointer including failure');}
for(let v of D.camera_clear.clear_gate){let {b,pool,s,k,vp}=setup();s.state=5;s.requested=5;s.limit_right=2560;b.camera_right=2560;k.xu=v.x*256;k.yu=238*256;k.contacts=v.floor;c.chaos_59_clear(b,pool,s,k,true,vp);eq(s.type,v.result.type,'floor gate');eq(k.next,v.result.player.requested,'state20');eq([b.camera_left,b.camera_right],v.limits,'restored limits');if(v.floor&2){eq(g.chaosBossNextAct,{zone:5,act:0});eq(b.spawns.map(e=>[e[1],e[2]]),[[10,0]]);}}
for(let width of [256,348,640]){let {b,vp}=setup();vp=c.chaos_vp_new(1500,0,width,192);b.pan_x=1728;b.pan_y=78;let xy=[1500,0];for(let i=0;i<300;i++)xy=c.chaos_59_pan(b,vp,...xy);eq(xy,[1727,78],'exclusive camera settle');}
const O=require('./aqz-p4/callback-oracle.json');
for(let v of O.rows){let e=v.initial,{b,pool,s,k,vp}=setup(e.type);if(e.type!==89)pool.slots[7]=c.chaos_59_slot(89,0,1856,160,0);let parent=pool.slots[7];Object.assign(parent,{counter:e.fixed_parent[0],field23:e.fixed_parent[5],field24:e.fixed_parent[6],field34:e.fixed_parent[22]});for(let [a,b]of Object.entries({state:'state',requested:'request',frame:'frame',timer:'duration',vx:'vx',vy:'vy',angle:'angle',saved_request:'saved_request',counter:'counter30',cooldown:'cooldown31',contact:'contact',field23:'field23',field24:'field24',hp:'hp',field34:'field34',field35:'field35',field38:'field38',parameter:'parameter',flags3:'flags3'}))s[a]=e[b];s.xu=e.x*256+e.fractions[0];s.yu=e.y*256+e.fractions[1];s.delay=O.rows.indexOf(v)%8;s.asleep=!!(e.flags4&64);k.xu=e.player.x*256;k.yu=e.player.y*256;k.move=e.player.flags;c.chaos_59_load_frame(s);c.chaos_59_callback(b,pool,s,v.callback,k,true,vp);cmp(s,v.result,'callback '+v.callback.toString(16)+' case '+O.rows.indexOf(v));}
for(let state of [...Array(4).keys(),...Array.from({length:16},(_,i)=>i+5)]){let {b,pool,s,k,vp}=setup();Object.assign(s,{state,requested:state,frame:0,counter:6,ex:0,ey:0});for(let v of O.script_rows.filter(v=>v.state===state)){c.chaos_59_script(b,pool,s,k,true,vp);cmp(s,v.result,'natural state '+state+' script call '+v.u);}}
for(let v0 of D.boundaries['5a_contact_return']){let v={result:v0};let {b,pool,s,k,vp}=setup(90);pool.slots[7]=c.chaos_59_slot(89,0,1856,160,0);pool.slots[7].field34=6;s.state=3;s.requested=3;s.frame=28;s.hp=v.result.hp===255?0:1;s.contact=v.result.contact;s.saved_request=1;c.chaos_59_callback(b,pool,s,0xACE3,k,true,vp);cmp(s,v.result,'5A two-response');eq(pool.slots[7].field34,v.result.fixed_parent[22]);}
for(let p=0;p<7;p++){let {b,pool,s,k,vp}=setup(92);pool.slots[7]=c.chaos_59_slot(89,0,0,0,0);pool.slots[7].field23=255;s.parameter=p;s.saved_request=128;c.chaos_59_callback(b,pool,s,0xADBE,k,true,vp);let start=[s.xu,s.yu];for(let i=0;i<16+32*p;i++){c.chaos_59_callback(b,pool,s,0xAE27,k,true,vp);eq(s.requested,5);eq([s.xu,s.yu],start);}c.chaos_59_callback(b,pool,s,0xAE27,k,true,vp);eq([s.requested,s.cooldown],[3,4]);}
{let {b,pool,s,k,vp}=setup();s.counter=96;s.cooldown=48;s.vy=-256;let y=s.yu;for(let i=0;i<47;i++)c.chaos_59_callback(b,pool,s,0xAB60,k,false,vp);eq([s.yu,s.cooldown],[y,1]);for(let i=0;i<97;i++)c.chaos_59_callback(b,pool,s,0xAB60,k,false,vp);eq([s.requested,s.counter,s.cooldown,s.vy],[13,0,1,0]);eq(s.yu,y-97*256);}
for(let fill of [0,1])for(let phase=0;phase<4;phase++)for(let sx=-129;sx<386;sx++){let {b,pool}=setup();pool.slots[7]=c.chaos_s2_slot();b.record=[1,1856,238,89,0,0];b.chaosInitialFillDone=!!fill;b.d2e2=phase;let vp=c.chaos_vp_new(1856-sx,138,256,192);eq(c.chaos_59_scan(b,pool,vp),phase===0&&D.camera_clear.scanner[String(fill)].includes(sx),'canonical mapped scan phase');}
fs.mkdirSync(root+'/build/aqz-p4',{recursive:true});fs.writeFileSync(root+'/build/aqz-p4/runtime-results.json',JSON.stringify({assertions:checks},null,2));console.log({checks});
