/// Generated by POC_notes/generate_sez_s5.py; Research eff4cecf03bfcef8638b39c0f7676abbfd32f26e.
/// Numeric ids only (no ROM bytes): state tables/records for $54/$55 and the shared $12/$34/$0A/$0F scripts, constants of boss-54-runtime.json.
#macro CHAOS_54_ANCHOR_X 3200
#macro CHAOS_54_ANCHOR_Y 622
#macro CHAOS_54_TOKEN 5
#macro CHAOS_54_TRIGGER_X 160
#macro CHAOS_54_TRIGGER_Y 304
#macro CHAOS_54_COMBAT_X 3136
#macro CHAOS_54_COMBAT_Y 430
#macro CHAOS_54_COMBAT_VY 192
#macro CHAOS_54_CAMERA_X 2976
#macro CHAOS_54_CAMERA_Y 462
#macro CHAOS_54_SETTLED_X 2975
#macro CHAOS_54_RIGHT_LIMIT 3840
#macro CHAOS_54_BOTTOM_INITIAL 784
#macro CHAOS_54_BOTTOM_LIMIT 462
#macro CHAOS_54_HP 8
#macro CHAOS_54_COOLDOWN 18
#macro CHAOS_54_HIT_DY 16
#macro CHAOS_54_Y_LAND 622
#macro CHAOS_54_Y_DROP 610
#macro CHAOS_54_CHILD_Y 626
#macro CHAOS_54_SCREEN_ESCAPE 208
#macro CHAOS_54_SCREEN_STOP 212
#macro CHAOS_54_EDGE_ESCAPE -48
#macro CHAOS_54_EDGE_STOP -44
#macro CHAOS_54_MIRROR_ESCAPE 48
#macro CHAOS_54_MIRROR_STOP 44
#macro CHAOS_54_BOUNCE_DX 96
#macro CHAOS_54_BOUNCE_VX 128
#macro CHAOS_54_BOUNCE_VY -896
#macro CHAOS_54_BOUNCE_VY_THIRD -1152
#macro CHAOS_54_BOUNCE_CYCLE 3
#macro CHAOS_54_GRAVITY_RISE 24
#macro CHAOS_54_GRAVITY_FALL 48
#macro CHAOS_54_GRAVITY_ESCAPE 32
#macro CHAOS_54_CHILD_VX -768
#macro CHAOS_54_CHILD_VY 704
#macro CHAOS_54_CHILD_EX 2
#macro CHAOS_54_CHILD_EY 4
#macro CHAOS_54_PLAYER_CLAMP_LEFT 16
#macro CHAOS_54_PLAYER_CLAMP_RIGHT -9
#macro CHAOS_54_GUARD_LEFT 32
#macro CHAOS_54_GUARD_RIGHT -32
#macro CHAOS_54_LEAD_RIGHT 104
#macro CHAOS_54_LEAD_LEFT 136
#macro CHAOS_54_LEAD_SLEW 1
#macro CHAOS_54_DEADZONE 8
#macro CHAOS_54_FOLLOW_RIGHT 7
#macro CHAOS_54_FOLLOW_LEFT -7
#macro CHAOS_54_RIGHT_FRAME 256
#macro CHAOS_54_FLASH_FIRST 4
#macro CHAOS_54_FLASH_LAST 7
#macro CHAOS_54_FLASH_END 8
#macro CHAOS_54_FLASH_SLOTS 4
#macro CHAOS_54_SND_ATTACK 182
#macro CHAOS_54_SND_EXPLOSION 196
#macro CHAOS_54_SND_CLEAR 151
#macro CHAOS_54_SND_MUSIC 140
function chaos_54_destination() { return {zone:3,act:0}; }
function chaos_54_extent(cp_type,cp_frame) { switch (cp_type) {
case 84: switch (cp_frame) {
case 1: return [20, 80];
case 2: return [20, 80];
case 3: return [20, 80];
case 4: return [20, 80];
case 5: return [20, 80];
case 6: return [20, 80];
case 7: return [20, 80];
case 8: return [20, 80];
case 15: return [20, 64];
case 16: return [20, 64];
} break;
case 85: switch (cp_frame) {
case 17: return [4, 16];
case 18: return [4, 16];
case 19: return [4, 16];
} break;
case 18: switch (cp_frame) {
case 0: return [0, 0];
} break;
case 52: switch (cp_frame) {
case 0: return [0, 0];
case 1: return [4, 16];
case 2: return [8, 16];
case 3: return [8, 16];
case 4: return [4, 16];
} break;
case 10: switch (cp_frame) {
case 0: return [0, 0];
case 5: return [4, 16];
case 6: return [4, 16];
} break;
case 15: switch (cp_frame) {
case 0: return [0, 0];
case 7: return [4, 16];
case 8: return [8, 16];
case 9: return [8, 16];
} break;
} return [0, 0]; }
function chaos_54_table(cp_type) { switch (cp_type) {
case 10: return [40030, 39912, 40036];
case 15: return [40915, 40921, 40921, 40971, 41016];
case 18: return [41561, 41567];
case 52: return [35815, 35821, 35859];
case 84: return [38321, 38330, 38336, 41462, 38348, 38430, 41468, 41474, 41532, 41550, 41565, 41575, 41601];
case 85: return [42077, 42083, 42089, 42095];
} return []; }
function chaos_54_record(cp_type,cp_pc) { switch (cp_type) {
case 10: switch (cp_pc) {
case 39912: return [39916, -1, 4, 5, 815];
case 39916: return [39920, -1, 4, 6, 815];
case 39920: return [39924, -1, 4, 5, 815];
case 39924: return [39928, -1, 4, 6, 815];
case 39928: return [39932, -1, 4, 5, 815];
case 39932: return [39936, -1, 4, 6, 815];
case 39936: return [39940, -1, 4, 5, 815];
case 39940: return [39944, -1, 4, 6, 842];
case 39944: return [39946, 0];
case 40030: return [40034, -1, 224, 0, 40070];
case 40034: return [40036, 0];
case 40036: return [40040, -1, 8, 0, 815];
case 40040: return [40044, 1, 40089];
case 40044: return [40052, 4, 10, 0, -12, 255];
case 40052: return [40056, -1, 8, 0, 815];
case 40056: return [40060, 1, 40089];
case 40060: return [40068, 4, 10, 0, -8, 255];
case 40068: return [40070, 0];
} break;
case 15: switch (cp_pc) {
case 40915: return [40919, -1, 1, 0, 41056];
case 40919: return [40921, 0];
case 40921: return [40925, -1, 1, 0, 1007];
case 40925: return [40929, -1, 4, 7, 815];
case 40929: return [40933, -1, 4, 8, 815];
case 40933: return [40937, -1, 4, 9, 815];
case 40937: return [40941, -1, 4, 7, 815];
case 40941: return [40945, -1, 4, 8, 815];
case 40945: return [40949, -1, 8, 9, 815];
case 40949: return [40953, -1, 4, 8, 815];
case 40953: return [40957, -1, 4, 7, 815];
case 40957: return [40961, 1, 41191];
case 40961: return [40965, -1, 1, 7, 815];
case 40965: return [40969, -1, 128, 0, 41158];
case 40969: return [40971, 0];
case 40971: return [40974, 6, 171];
case 40974: return [40978, -1, 4, 7, 815];
case 40978: return [40982, -1, 4, 8, 815];
case 40982: return [40986, -1, 4, 9, 815];
case 40986: return [40990, -1, 4, 7, 815];
case 40990: return [40994, -1, 4, 8, 815];
case 40994: return [40998, -1, 8, 9, 815];
case 40998: return [41002, -1, 4, 8, 815];
case 41002: return [41006, -1, 4, 7, 815];
case 41006: return [41010, -1, 1, 7, 815];
case 41010: return [41014, -1, 128, 0, 41158];
case 41014: return [41016, 0];
case 41016: return [41022, 2, 256, 0];
case 41022: return [41025, 14, 16];
case 41025: return [41029, -1, 4, 9, 41047];
case 41029: return [41033, -1, 4, 8, 41047];
case 41033: return [41037, -1, 4, 7, 41047];
case 41037: return [41041, 15, 41025];
case 41041: return [41045, -1, 224, 9, 41051];
case 41045: return [41047, 0];
} break;
case 18: switch (cp_pc) {
case 41561: return [41565, -1, 1, 0, 41573];
case 41565: return [41567, 0];
case 41567: return [41571, -1, 128, 0, 41582];
case 41571: return [41573, 0];
} break;
case 52: switch (cp_pc) {
case 35815: return [35819, -1, 224, 0, 35905];
case 35819: return [35821, 0];
case 35821: return [35825, -1, 1, 0, 1007];
case 35825: return [35829, -1, 4, 4, 35999];
case 35829: return [35833, -1, 4, 1, 35999];
case 35833: return [35837, -1, 4, 2, 35999];
case 35837: return [35841, -1, 4, 3, 35999];
case 35841: return [35845, -1, 4, 2, 35999];
case 35845: return [35849, -1, 3, 3, 35999];
case 35849: return [35853, -1, 1, 0, 36093];
case 35853: return [35857, -1, 1, 0, 36003];
case 35857: return [35859, 0];
case 35859: return [35863, -1, 1, 0, 1007];
case 35863: return [35867, -1, 6, 4, 35999];
case 35867: return [35871, -1, 6, 1, 35999];
case 35871: return [35875, -1, 6, 2, 35999];
case 35875: return [35879, -1, 6, 3, 35999];
case 35879: return [35883, -1, 6, 2, 35999];
case 35883: return [35887, -1, 8, 3, 35999];
case 35887: return [35891, -1, 6, 2, 35999];
case 35891: return [35895, -1, 3, 3, 35999];
case 35895: return [35899, -1, 1, 0, 36093];
case 35899: return [35903, -1, 1, 0, 36003];
case 35903: return [35905, 0];
} break;
case 84: switch (cp_pc) {
case 38321: return [38324, 6, 140];
case 38324: return [38328, -1, 224, 0, 38732];
case 38328: return [38330, 0];
case 38330: return [38334, -1, 224, 0, 38769];
case 38334: return [38336, 0];
case 38336: return [38340, -1, 224, 0, 38849];
case 38340: return [38342, 0];
case 38348: return [38356, 4, 52, -8, 0, 4];
case 38356: return [38362, 5, 39454, 815];
case 38362: return [38370, 4, 52, 8, 0, 4];
case 38370: return [38374, -1, 1, 0, 815];
case 38374: return [38382, 4, 52, 0, -16, 4];
case 38382: return [38388, 5, 39465, 815];
case 38388: return [38396, 4, 52, -8, -24, 4];
case 38396: return [38400, -1, 1, 0, 815];
case 38400: return [38408, 4, 52, -8, -24, 4];
case 38408: return [38411, 14, 24];
case 38411: return [38417, 5, 39471, 815];
case 38417: return [38421, -1, 2, 0, 815];
case 38421: return [38425, 15, 38411];
case 38425: return [38428, 3, 5];
case 38428: return [38430, 0];
case 38430: return [38434, -1, 224, 0, 33213];
case 38434: return [38436, 0];
case 41462: return [41466, -1, 224, 0, 41617];
case 41466: return [41468, 0];
case 41468: return [41472, -1, 224, 1, 41706];
case 41472: return [41474, 0];
case 41474: return [41477, 14, 2];
case 41477: return [41481, -1, 2, 3, 41722];
case 41481: return [41485, -1, 2, 4, 41722];
case 41485: return [41489, 15, 41477];
case 41489: return [41492, 14, 3];
case 41492: return [41500, 4, 85, -16, -36, 0];
case 41500: return [41504, -1, 3, 3, 41722];
case 41504: return [41508, -1, 3, 4, 41722];
case 41508: return [41512, 15, 41492];
case 41512: return [41516, -1, 2, 1, 41722];
case 41516: return [41520, -1, 8, 3, 41722];
case 41520: return [41524, -1, 2, 2, 41722];
case 41524: return [41528, -1, 8, 4, 41722];
case 41528: return [41532, 7, 41512];
case 41532: return [41536, -1, 4, 5, 41746];
case 41536: return [41540, -1, 4, 7, 41746];
case 41540: return [41544, -1, 4, 6, 41746];
case 41544: return [41548, -1, 4, 8, 41746];
case 41548: return [41550, 0];
case 41550: return [41553, 6, 166];
case 41553: return [41557, -1, 2, 15, 41770];
case 41557: return [41561, -1, 2, 16, 41770];
case 41561: return [41565, 7, 41553];
case 41565: return [41569, -1, 2, 15, 41785];
case 41569: return [41573, -1, 2, 16, 41785];
case 41573: return [41575, 0];
case 41575: return [41581, 2, 0, -2048];
case 41581: return [41585, -1, 4, 5, 41878];
case 41585: return [41589, -1, 4, 7, 41878];
case 41589: return [41593, -1, 4, 6, 41878];
case 41593: return [41597, -1, 4, 8, 41878];
case 41597: return [41601, 7, 41581];
case 41601: return [41605, -1, 32, 0, 815];
case 41605: return [41611, 2, 0, 512];
case 41611: return [41615, -1, 224, 0, 41903];
case 41615: return [41617, 0];
} break;
case 85: switch (cp_pc) {
case 42077: return [42081, -1, 8, 0, 42113];
case 42081: return [42083, 0];
case 42083: return [42087, -1, 8, 17, 42136];
case 42087: return [42089, 0];
case 42089: return [42093, -1, 8, 17, 42141];
case 42093: return [42095, 0];
case 42095: return [42099, -1, 3, 17, 42148];
case 42099: return [42103, -1, 3, 19, 42148];
case 42103: return [42107, -1, 3, 18, 42148];
case 42107: return [42111, -1, 3, 19, 42148];
case 42111: return [42113, 0];
} break;
} return []; }
