/// GENERATED by POC_notes/generate_thz3_boss_data.js from Research implementation-manifest.json.
/// Source SHA-256: 2eb5d139a3ae8fc44428432f7981f4057293d915ff62305090a5262386c4bdd6
/// Support cache SHA-256: 4af3e660387f6a8bf012088fbef90d1ced463467b2293bc2c30912452af9d6a7
/// Object $50 mapping SHA-256: 327c50bc2a1af4f60a2eef780bda8eaea8a656f7239dde37ecfe554a9f0dca4d
#macro CHAOS_BOSS_WORLD_X 1936
#macro CHAOS_BOSS_WORLD_Y 238
#macro CHAOS_BOSS_CREATE_MIN_OUT 32
#macro CHAOS_BOSS_CREATE_MAX_OUT 95
#macro CHAOS_BOSS_TRIGGER_X 160
#macro CHAOS_BOSS_TRIGGER_Y 256
#macro CHAOS_BOSS_CAMERA_X 1679
#macro CHAOS_BOSS_CAMERA_Y 78
#macro CHAOS_BOSS_PAN_LIMIT_X 1680
#macro CHAOS_BOSS_ARENA_LEFT 1695
#macro CHAOS_BOSS_ARENA_RIGHT 1926
#macro CHAOS_BOSS_PATROL_LEFT 1735
#macro CHAOS_BOSS_PATROL_RIGHT 1879
#macro CHAOS_BOSS_HP 8
#macro CHAOS_BOSS_DEFEAT_UPDATES 148
#macro CHAOS_BOSS_EXT_X 20
#macro CHAOS_BOSS_EXT_Y 48
#macro CHAOS_BOSS_PLAYER_EXT_X 8
#macro CHAOS_BOSS_PLAYER_EXT_Y 24
#macro CHAOS_BOSS_DRAW_Y_OFFSET 18
#macro CHAOS_BOSS_CONVERTED -2
function chaos_boss_vulnerable_state(cp_state) { return cp_state == 6 || cp_state == 9 || cp_state == 12 || cp_state == 15; }
function chaos_boss_puff_offsets() { return [[-8,0],[8,0],[0,-16],[-8,-24],[-8,-24]]; }
function chaos_boss_puff_lifetimes() { return [129,249,129,248,129]; }
function chaos_boss_state_ids() { return [0,1,2,3,18,6,9,12,15,7,10,13,16,8,11,14,17,4,5]; }
function chaos_boss_mapping_data(cp_state) { switch (cp_state) {
case 0: return {mirrored:false,loop:0,records:[[224,0]]};
case 1: return {mirrored:false,loop:0,records:[[224,0]]};
case 2: return {mirrored:false,loop:0,records:[[224,0]]};
case 3: return {mirrored:false,loop:0,records:[[224,0]]};
case 4: return {mirrored:false,loop:0,records:[[1,0],[1,0],[2,0]]};
case 5: return {mirrored:false,loop:0,records:[[224,0]]};
case 6: return {mirrored:false,loop:0,records:[[16,1],[16,2]]};
case 7: return {mirrored:false,loop:4,records:[[2,3],[2,1],[3,3],[3,1],[4,4],[4,2],[4,4],[4,2],[4,3],[4,1],[4,3],[4,1]]};
case 8: return {mirrored:false,loop:0,records:[[4,1],[4,2]]};
case 9: return {mirrored:false,loop:0,records:[[8,5]]};
case 10: return {mirrored:false,loop:4,records:[[2,5],[2,6],[3,5],[3,6],[4,5],[4,6]]};
case 11: return {mirrored:false,loop:0,records:[[8,5]]};
case 12: return {mirrored:true,loop:0,records:[[16,1],[16,2]]};
case 13: return {mirrored:true,loop:4,records:[[2,1],[2,3],[3,1],[3,3],[4,2],[4,4],[4,2],[4,4],[4,1],[4,3],[4,1],[4,3]]};
case 14: return {mirrored:true,loop:0,records:[[4,1],[4,2]]};
case 15: return {mirrored:false,loop:0,records:[[8,5]]};
case 16: return {mirrored:false,loop:4,records:[[2,6],[2,5],[3,6],[3,5],[4,6],[4,5]]};
case 17: return {mirrored:false,loop:0,records:[[16,5]]};
case 18: return {mirrored:false,loop:0,records:[[16,1],[16,2]]};
default: return {mirrored:false,loop:0,records:[[1,0]]}; } }
function chaos_boss_mapping(cp_state, cp_age) {
    var cp_data=chaos_boss_mapping_data(cp_state);
    var cp_total=0,cp_loop_at=0;
    for (var cp_i=0;cp_i<array_length(cp_data.records);cp_i++) {
        if (cp_i == cp_data.loop) cp_loop_at=cp_total;
        cp_total += cp_data.records[cp_i][0];
    }
    var cp_time=max(0,cp_age);
    if (cp_time >= cp_total) cp_time=cp_loop_at+((cp_time-cp_loop_at) mod (cp_total-cp_loop_at));
    for (var cp_i=0;cp_i<array_length(cp_data.records);cp_i++) {
        if (cp_time < cp_data.records[cp_i][0]) return {frame:cp_data.records[cp_i][1],mirrored:cp_data.mirrored};
        cp_time -= cp_data.records[cp_i][0];
    }
    return {frame:0,mirrored:cp_data.mirrored};
}
