function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // OBJ_system
	global.__objectDepths[1] = 0; // OBJ_system_start
	global.__objectDepths[2] = -1; // OBJ_system_zone
	global.__objectDepths[3] = 0; // OBJ_system_save_data
	global.__objectDepths[4] = 0; // OBJ_menu_opening
	global.__objectDepths[5] = 0; // OBJ_menu_title
	global.__objectDepths[6] = 0; // OBJ_menu_title_options
	global.__objectDepths[7] = 0; // OBJ_menu_options
	global.__objectDepths[8] = 0; // OBJ_menu_data_select
	global.__objectDepths[9] = 0; // OBJ_menu_data_button_del
	global.__objectDepths[10] = 0; // OBJ_menu_data_card_1
	global.__objectDepths[11] = 0; // OBJ_menu_data_card_2
	global.__objectDepths[12] = 0; // OBJ_menu_data_card_3
	global.__objectDepths[13] = 0; // OBJ_menu_data_card_4
	global.__objectDepths[14] = 0; // OBJ_menu_data_card_5
	global.__objectDepths[15] = 0; // OBJ_menu_point_counter
	global.__objectDepths[16] = 0; // OBJ_menu_game_over
	global.__objectDepths[17] = -999; // OBJ_count_rings
	global.__objectDepths[18] = -999; // OBJ_count_time
	global.__objectDepths[19] = -999; // OBJ_count_lifes
	global.__objectDepths[20] = -9999; // OBJ_virtual_controller_menus
	global.__objectDepths[21] = -9999; // OBJ_virtual_controller
	global.__objectDepths[22] = -999999; // OBJ_pause
	global.__objectDepths[23] = 0; // OBJ_player
	global.__objectDepths[24] = -50; // OBJ_player_climbing
	global.__objectDepths[25] = -50; // OBJ_player_lost_a
	global.__objectDepths[26] = -50; // OBJ_player_lost_b
	global.__objectDepths[27] = -99; // OBJ_player_death
	global.__objectDepths[28] = -50; // OBJ_player_plate
	global.__objectDepths[29] = -50; // OBJ_player_super_transform
	global.__objectDepths[30] = -50; // OBJ_player_char
	global.__objectDepths[31] = -50; // OBJ_player_char_spin
	global.__objectDepths[32] = -52; // OBJ_power_super_stars
	global.__objectDepths[33] = -52; // OBJ_power_invincibility
	global.__objectDepths[34] = -52; // OBJ_power_shield
	global.__objectDepths[35] = -52; // OBJ_power_shield_magnet
	global.__objectDepths[36] = -52; // OBJ_power_shield_flame
	global.__objectDepths[37] = -53; // OBJ_power_shield_flame_jump
	global.__objectDepths[38] = 0; // OBJ_collision_floor
	global.__objectDepths[39] = 0; // OBJ_collision_floor_edge
	global.__objectDepths[40] = 0; // OBJ_collision_floor_ghost
	global.__objectDepths[41] = 0; // OBJ_collision_wall
	global.__objectDepths[42] = 0; // OBJ_collision_wall_edge
	global.__objectDepths[43] = 0; // OBJ_collision_roof
	global.__objectDepths[44] = 0; // OBJ_collision_ramp_1
	global.__objectDepths[45] = 0; // OBJ_collision_ramp_2
	global.__objectDepths[46] = 0; // OBJ_collision_ramp_1_ghost
	global.__objectDepths[47] = 0; // OBJ_collision_ramp_2_ghost
	global.__objectDepths[48] = 0; // OBJ_collision_platforms
	global.__objectDepths[49] = 0; // OBJ_collision_death
	global.__objectDepths[50] = 1; // OBJ_collision_water
	global.__objectDepths[51] = 10; // OBJ_platform_fake_wall_solid
	global.__objectDepths[52] = -90; // OBJ_platform_fake_wall_destroy_r_1
	global.__objectDepths[53] = -90; // OBJ_platform_fake_wall_destroy_r_2
	global.__objectDepths[54] = -90; // OBJ_platform_fake_wall_destroy_l_1
	global.__objectDepths[55] = -90; // OBJ_platform_fake_wall_destroy_l_2
	global.__objectDepths[56] = -10; // OBJ_platform_left_right
	global.__objectDepths[57] = -10; // OBJ_platform_up_down
	global.__objectDepths[58] = -10; // OBJ_platform_fall
	global.__objectDepths[59] = 0; // OBJ_platform_bridge
	global.__objectDepths[60] = -10; // OBJ_platform_roll
	global.__objectDepths[61] = -10; // OBJ_platform_belt
	global.__objectDepths[62] = 10; // OBJ_platform_fake_wall
	global.__objectDepths[63] = -10; // OBJ_ring
	global.__objectDepths[64] = -10; // OBJ_ring_big
	global.__objectDepths[65] = -10; // OBJ_chao_emerald_1
	global.__objectDepths[66] = -10; // OBJ_chao_emerald_2
	global.__objectDepths[67] = -10; // OBJ_chao_emerald_3
	global.__objectDepths[68] = -10; // OBJ_chao_emerald_4
	global.__objectDepths[69] = -10; // OBJ_chao_emerald_5
	global.__objectDepths[70] = -10; // OBJ_chao_emerald_6
	global.__objectDepths[71] = -10; // OBJ_chao_emerald_7
	global.__objectDepths[72] = 0; // OBJ_monitors
	global.__objectDepths[73] = -10; // OBJ_monitor_ring
	global.__objectDepths[74] = -10; // OBJ_monitor_life
	global.__objectDepths[75] = -10; // OBJ_monitor_checkpoint
	global.__objectDepths[76] = -10; // OBJ_monitor_invincibility
	global.__objectDepths[77] = -10; // OBJ_monitor_shield
	global.__objectDepths[78] = -10; // OBJ_monitor_shield_magnet
	global.__objectDepths[79] = -10; // OBJ_monitor_shield_flame
	global.__objectDepths[80] = -10; // OBJ_monitor_eggman
	global.__objectDepths[81] = -10; // OBJ_plate
	global.__objectDepths[82] = -48; // OBJ_spring_1
	global.__objectDepths[83] = -48; // OBJ_spring_2
	global.__objectDepths[84] = 0; // OBJ_badniks
	global.__objectDepths[85] = -49; // OBJ_badnik_1
	global.__objectDepths[86] = -999999; // OBJ_effect_fade_in
	global.__objectDepths[87] = -999999; // OBJ_effect_fade_out
	global.__objectDepths[88] = -10; // OBJ_ring_stars
	global.__objectDepths[89] = -10; // OBJ_emerald_stars
	global.__objectDepths[90] = -12; // OBJ_explosion
	global.__objectDepths[91] = -12; // OBJ_explosion_silent


	global.__objectNames[0] = "OBJ_system";
	global.__objectNames[1] = "OBJ_system_start";
	global.__objectNames[2] = "OBJ_system_zone";
	global.__objectNames[3] = "OBJ_system_save_data";
	global.__objectNames[4] = "OBJ_menu_opening";
	global.__objectNames[5] = "OBJ_menu_title";
	global.__objectNames[6] = "OBJ_menu_title_options";
	global.__objectNames[7] = "OBJ_menu_options";
	global.__objectNames[8] = "OBJ_menu_data_select";
	global.__objectNames[9] = "OBJ_menu_data_button_del";
	global.__objectNames[10] = "OBJ_menu_data_card_1";
	global.__objectNames[11] = "OBJ_menu_data_card_2";
	global.__objectNames[12] = "OBJ_menu_data_card_3";
	global.__objectNames[13] = "OBJ_menu_data_card_4";
	global.__objectNames[14] = "OBJ_menu_data_card_5";
	global.__objectNames[15] = "OBJ_menu_point_counter";
	global.__objectNames[16] = "OBJ_menu_game_over";
	global.__objectNames[17] = "OBJ_count_rings";
	global.__objectNames[18] = "OBJ_count_time";
	global.__objectNames[19] = "OBJ_count_lifes";
	global.__objectNames[20] = "OBJ_virtual_controller_menus";
	global.__objectNames[21] = "OBJ_virtual_controller";
	global.__objectNames[22] = "OBJ_pause";
	global.__objectNames[23] = "OBJ_player";
	global.__objectNames[24] = "OBJ_player_climbing";
	global.__objectNames[25] = "OBJ_player_lost_a";
	global.__objectNames[26] = "OBJ_player_lost_b";
	global.__objectNames[27] = "OBJ_player_death";
	global.__objectNames[28] = "OBJ_player_plate";
	global.__objectNames[29] = "OBJ_player_super_transform";
	global.__objectNames[30] = "OBJ_player_char";
	global.__objectNames[31] = "OBJ_player_char_spin";
	global.__objectNames[32] = "OBJ_power_super_stars";
	global.__objectNames[33] = "OBJ_power_invincibility";
	global.__objectNames[34] = "OBJ_power_shield";
	global.__objectNames[35] = "OBJ_power_shield_magnet";
	global.__objectNames[36] = "OBJ_power_shield_flame";
	global.__objectNames[37] = "OBJ_power_shield_flame_jump";
	global.__objectNames[38] = "OBJ_collision_floor";
	global.__objectNames[39] = "OBJ_collision_floor_edge";
	global.__objectNames[40] = "OBJ_collision_floor_ghost";
	global.__objectNames[41] = "OBJ_collision_wall";
	global.__objectNames[42] = "OBJ_collision_wall_edge";
	global.__objectNames[43] = "OBJ_collision_roof";
	global.__objectNames[44] = "OBJ_collision_ramp_1";
	global.__objectNames[45] = "OBJ_collision_ramp_2";
	global.__objectNames[46] = "OBJ_collision_ramp_1_ghost";
	global.__objectNames[47] = "OBJ_collision_ramp_2_ghost";
	global.__objectNames[48] = "OBJ_collision_platforms";
	global.__objectNames[49] = "OBJ_collision_death";
	global.__objectNames[50] = "OBJ_collision_water";
	global.__objectNames[51] = "OBJ_platform_fake_wall_solid";
	global.__objectNames[52] = "OBJ_platform_fake_wall_destroy_r_1";
	global.__objectNames[53] = "OBJ_platform_fake_wall_destroy_r_2";
	global.__objectNames[54] = "OBJ_platform_fake_wall_destroy_l_1";
	global.__objectNames[55] = "OBJ_platform_fake_wall_destroy_l_2";
	global.__objectNames[56] = "OBJ_platform_left_right";
	global.__objectNames[57] = "OBJ_platform_up_down";
	global.__objectNames[58] = "OBJ_platform_fall";
	global.__objectNames[59] = "OBJ_platform_bridge";
	global.__objectNames[60] = "OBJ_platform_roll";
	global.__objectNames[61] = "OBJ_platform_belt";
	global.__objectNames[62] = "OBJ_platform_fake_wall";
	global.__objectNames[63] = "OBJ_ring";
	global.__objectNames[64] = "OBJ_ring_big";
	global.__objectNames[65] = "OBJ_chao_emerald_1";
	global.__objectNames[66] = "OBJ_chao_emerald_2";
	global.__objectNames[67] = "OBJ_chao_emerald_3";
	global.__objectNames[68] = "OBJ_chao_emerald_4";
	global.__objectNames[69] = "OBJ_chao_emerald_5";
	global.__objectNames[70] = "OBJ_chao_emerald_6";
	global.__objectNames[71] = "OBJ_chao_emerald_7";
	global.__objectNames[72] = "OBJ_monitors";
	global.__objectNames[73] = "OBJ_monitor_ring";
	global.__objectNames[74] = "OBJ_monitor_life";
	global.__objectNames[75] = "OBJ_monitor_checkpoint";
	global.__objectNames[76] = "OBJ_monitor_invincibility";
	global.__objectNames[77] = "OBJ_monitor_shield";
	global.__objectNames[78] = "OBJ_monitor_shield_magnet";
	global.__objectNames[79] = "OBJ_monitor_shield_flame";
	global.__objectNames[80] = "OBJ_monitor_eggman";
	global.__objectNames[81] = "OBJ_plate";
	global.__objectNames[82] = "OBJ_spring_1";
	global.__objectNames[83] = "OBJ_spring_2";
	global.__objectNames[84] = "OBJ_badniks";
	global.__objectNames[85] = "OBJ_badnik_1";
	global.__objectNames[86] = "OBJ_effect_fade_in";
	global.__objectNames[87] = "OBJ_effect_fade_out";
	global.__objectNames[88] = "OBJ_ring_stars";
	global.__objectNames[89] = "OBJ_emerald_stars";
	global.__objectNames[90] = "OBJ_explosion";
	global.__objectNames[91] = "OBJ_explosion_silent";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
