/// Generated by POC_notes/import_mghz_boss.py; Research e0f42f89a6ecabd6ed504ef318ea8170ce1a3f1f.
/// Numeric ids only (no ROM bytes): state tables/records for $56/$57/$58 and the shared $12/$34/$0A/$0F scripts.
#macro CHAOS_56_ANCHOR_X 3269
#macro CHAOS_56_ANCHOR_Y 288
#macro CHAOS_56_TOKEN 12
#macro CHAOS_56_TRIGGER_X 160
#macro CHAOS_56_TRIGGER_Y 304
#macro CHAOS_56_PAN_DX -208
#macro CHAOS_56_PAN_DY -32
#macro CHAOS_56_CAMERA_X 3061
#macro CHAOS_56_CAMERA_Y 256
#macro CHAOS_56_RISE_Y 288
#macro CHAOS_56_FALL_Y 430
#macro CHAOS_56_HP 10
#macro CHAOS_56_COOLDOWN 8
#macro CHAOS_56_CLEAR_X 3356
#macro CHAOS_56_RIGHT_LIMIT 3584
#macro CHAOS_56_PLAYER_CLAMP_LEFT 16
#macro CHAOS_56_PLAYER_CLAMP_RIGHT -9
#macro CHAOS_56_GUARD_LEFT 32
#macro CHAOS_56_GUARD_RIGHT -32
#macro CHAOS_56_EARLY_X 176
#macro CHAOS_56_EARLY_Y 120
#macro CHAOS_56_LEAD_RIGHT 104
#macro CHAOS_56_LEAD_LEFT 136
#macro CHAOS_56_LEAD_SLEW 1
#macro CHAOS_56_DEADZONE 8
#macro CHAOS_56_FOLLOW_RIGHT 7
#macro CHAOS_56_FOLLOW_LEFT -7
#macro CHAOS_56_RESTORED_RIGHT 3584
#macro CHAOS_56_RIGHT_FRAME 48
#macro CHAOS_56_FLASH_FIRST 4
#macro CHAOS_56_FLASH_LAST 7
#macro CHAOS_56_FLASH_END 8
#macro CHAOS_56_FLASH_SLOTS 4
#macro CHAOS_56_SND_LANDING 185
#macro CHAOS_56_SND_ATTACK 182
#macro CHAOS_56_SND_EXPLOSION 196
#macro CHAOS_56_SND_CLEAR 151
#macro CHAOS_56_SND_DEATH 150
function chaos_56_destination() { return {zone:4,act:0}; }
function chaos_56_throw_selector(cp_counter) { var cp_t = [8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 8, 8, 8, 8, 8, 9, 9, 8, 8, 8, 9, 8, 8, 9, 8, 9, 9, 8, 9, 8, 9, 9, 8, 9, 8, 8, 9, 9, 9, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 8, 8, 9, 8, 9, 8, 9, 8, 9, 8, 9, 9, 8, 8, 9, 9, 9, 8, 8, 8, 8, 8, 9, 9, 9, 8, 8, 9, 9, 8, 9, 9, 8, 9, 8, 9, 8, 8, 9, 8, 9, 9, 8, 8, 9, 9, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 8, 8, 8, 8, 9, 9, 8, 8, 9, 9, 8, 9, 8, 8, 9, 8, 9, 8, 9, 9, 8, 9, 9, 8, 8, 9, 9, 9, 8, 8, 8, 8, 8, 9, 9, 9, 8, 8, 9, 9, 8, 9, 8, 9, 8, 9, 8, 9, 8, 8, 9, 9, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 8, 8, 9, 8, 9, 9, 8, 9, 8, 9, 9, 8, 9, 8, 8, 9, 8, 8, 8, 9, 9, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 8, 8, 8, 8, 8, 8, 8]; return cp_t[cp_counter & 255]; }
function chaos_56_extent(cp_type,cp_frame) { switch (cp_type) {
case 86: case 87: case 88: switch (cp_frame) {
case 1: return [16, 48];
case 2: return [16, 48];
case 3: return [16, 48];
case 4: return [16, 48];
case 5: return [16, 48];
case 6: return [16, 48];
case 11: return [12, 16];
case 12: return [8, 16];
case 13: return [4, 16];
case 14: return [4, 16];
case 15: return [4, 16];
} break;
case 52: switch (cp_frame) {
case 0: return [0, 0];
case 1: return [4, 16];
case 2: return [8, 16];
case 3: return [8, 16];
case 4: return [4, 16];
} break;
case 10: switch (cp_frame) {
case 0: return [0, 0];
case 5: return [4, 16];
case 6: return [4, 16];
} break;
case 15: switch (cp_frame) {
case 0: return [0, 0];
case 7: return [4, 16];
case 8: return [8, 16];
case 9: return [8, 16];
} break;
} return [0, 0]; }
function chaos_56_table(cp_type) { switch (cp_type) {
case 10: return [40030, 39912, 40036];
case 15: return [40915, 40921, 40921, 40971, 41016];
case 18: return [41561, 41567];
case 52: return [35815, 35821, 35859];
case 86: return [38321, 38330, 38336, 42206, 38348, 38430, 42212, 42225, 42256, 42268, 42307, 42328, 42349];
case 87: return [42719, 42725, 42746, 42761];
case 88: return [42894, 42900];
} return []; }
function chaos_56_record(cp_type,cp_pc) { switch (cp_type) {
case 10: switch (cp_pc) {
case 39912: return [39916, -1, 4, 5, 815];
case 39916: return [39920, -1, 4, 6, 815];
case 39920: return [39924, -1, 4, 5, 815];
case 39924: return [39928, -1, 4, 6, 815];
case 39928: return [39932, -1, 4, 5, 815];
case 39932: return [39936, -1, 4, 6, 815];
case 39936: return [39940, -1, 4, 5, 815];
case 39940: return [39944, -1, 4, 6, 842];
case 39944: return [39946, 0];
case 40030: return [40034, -1, 224, 0, 40070];
case 40034: return [40036, 0];
case 40036: return [40040, -1, 8, 0, 815];
case 40040: return [40044, 1, 40089];
case 40044: return [40052, 4, 10, 0, -12, 255];
case 40052: return [40056, -1, 8, 0, 815];
case 40056: return [40060, 1, 40089];
case 40060: return [40068, 4, 10, 0, -8, 255];
case 40068: return [40070, 0];
} break;
case 15: switch (cp_pc) {
case 40915: return [40919, -1, 1, 0, 41056];
case 40919: return [40921, 0];
case 40921: return [40925, -1, 1, 0, 1007];
case 40925: return [40929, -1, 4, 7, 815];
case 40929: return [40933, -1, 4, 8, 815];
case 40933: return [40937, -1, 4, 9, 815];
case 40937: return [40941, -1, 4, 7, 815];
case 40941: return [40945, -1, 4, 8, 815];
case 40945: return [40949, -1, 8, 9, 815];
case 40949: return [40953, -1, 4, 8, 815];
case 40953: return [40957, -1, 4, 7, 815];
case 40957: return [40961, 1, 41191];
case 40961: return [40965, -1, 1, 7, 815];
case 40965: return [40969, -1, 128, 0, 41158];
case 40969: return [40971, 0];
case 40971: return [40974, 6, 171];
case 40974: return [40978, -1, 4, 7, 815];
case 40978: return [40982, -1, 4, 8, 815];
case 40982: return [40986, -1, 4, 9, 815];
case 40986: return [40990, -1, 4, 7, 815];
case 40990: return [40994, -1, 4, 8, 815];
case 40994: return [40998, -1, 8, 9, 815];
case 40998: return [41002, -1, 4, 8, 815];
case 41002: return [41006, -1, 4, 7, 815];
case 41006: return [41010, -1, 1, 7, 815];
case 41010: return [41014, -1, 128, 0, 41158];
case 41014: return [41016, 0];
case 41016: return [41022, 2, 256, 0];
case 41022: return [41025, 14, 16];
case 41025: return [41029, -1, 4, 9, 41047];
case 41029: return [41033, -1, 4, 8, 41047];
case 41033: return [41037, -1, 4, 7, 41047];
case 41037: return [41041, 15, 41025];
case 41041: return [41045, -1, 224, 9, 41051];
case 41045: return [41047, 0];
} break;
case 18: switch (cp_pc) {
case 41561: return [41565, -1, 1, 0, 41573];
case 41565: return [41567, 0];
case 41567: return [41571, -1, 128, 0, 41582];
case 41571: return [41573, 0];
} break;
case 52: switch (cp_pc) {
case 35815: return [35819, -1, 224, 0, 35905];
case 35819: return [35821, 0];
case 35821: return [35825, -1, 1, 0, 1007];
case 35825: return [35829, -1, 4, 4, 35999];
case 35829: return [35833, -1, 4, 1, 35999];
case 35833: return [35837, -1, 4, 2, 35999];
case 35837: return [35841, -1, 4, 3, 35999];
case 35841: return [35845, -1, 4, 2, 35999];
case 35845: return [35849, -1, 3, 3, 35999];
case 35849: return [35853, -1, 1, 0, 36093];
case 35853: return [35857, -1, 1, 0, 36003];
case 35857: return [35859, 0];
case 35859: return [35863, -1, 1, 0, 1007];
case 35863: return [35867, -1, 6, 4, 35999];
case 35867: return [35871, -1, 6, 1, 35999];
case 35871: return [35875, -1, 6, 2, 35999];
case 35875: return [35879, -1, 6, 3, 35999];
case 35879: return [35883, -1, 6, 2, 35999];
case 35883: return [35887, -1, 8, 3, 35999];
case 35887: return [35891, -1, 6, 2, 35999];
case 35891: return [35895, -1, 3, 3, 35999];
case 35895: return [35899, -1, 1, 0, 36093];
case 35899: return [35903, -1, 1, 0, 36003];
case 35903: return [35905, 0];
} break;
case 86: switch (cp_pc) {
case 38321: return [38324, 6, 140];
case 38324: return [38328, -1, 224, 0, 38732];
case 38328: return [38330, 0];
case 38330: return [38334, -1, 224, 0, 38769];
case 38334: return [38336, 0];
case 38336: return [38340, -1, 224, 0, 38849];
case 38340: return [38342, 0];
case 38348: return [38356, 4, 52, -8, 0, 4];
case 38356: return [38362, 5, 39454, 815];
case 38362: return [38370, 4, 52, 8, 0, 4];
case 38370: return [38374, -1, 1, 0, 815];
case 38374: return [38382, 4, 52, 0, -16, 4];
case 38382: return [38388, 5, 39465, 815];
case 38388: return [38396, 4, 52, -8, -24, 4];
case 38396: return [38400, -1, 1, 0, 815];
case 38400: return [38408, 4, 52, -8, -24, 4];
case 38408: return [38411, 14, 24];
case 38411: return [38417, 5, 39471, 815];
case 38417: return [38421, -1, 2, 0, 815];
case 38421: return [38425, 15, 38411];
case 38425: return [38428, 3, 5];
case 38428: return [38430, 0];
case 38430: return [38434, -1, 224, 0, 33213];
case 38434: return [38436, 0];
case 42206: return [42210, -1, 224, 0, 42358];
case 42210: return [42212, 0];
case 42212: return [42218, 2, 0, -256];
case 42218: return [42221, 14, 3];
case 42221: return [42225, 7, 42234];
case 42225: return [42231, 2, 0, 256];
case 42231: return [42234, 14, 2];
case 42234: return [42238, -1, 8, 1, 42391];
case 42238: return [42242, -1, 8, 2, 42391];
case 42242: return [42246, 15, 42234];
case 42246: return [42250, -1, 1, 2, 42391];
case 42250: return [42254, -1, 224, 2, 42423];
case 42254: return [42256, 0];
case 42256: return [42264, 4, 87, -20, -8, 0];
case 42264: return [42268, 7, 42276];
case 42268: return [42276, 4, 87, -16, -8, 1];
case 42276: return [42282, 2, -512, 0];
case 42282: return [42285, 14, 8];
case 42285: return [42289, -1, 2, 3, 42426];
case 42289: return [42293, -1, 2, 4, 42426];
case 42293: return [42297, 15, 42285];
case 42297: return [42301, -1, 1, 4, 42441];
case 42301: return [42305, -1, 224, 4, 42438];
case 42305: return [42307, 0];
case 42307: return [42310, 14, 10];
case 42310: return [42314, -1, 2, 6, 42458];
case 42314: return [42318, -1, 2, 5, 42458];
case 42318: return [42322, 15, 42310];
case 42322: return [42326, -1, 224, 5, 42438];
case 42326: return [42328, 0];
case 42328: return [42334, 2, 0, 0];
case 42334: return [42337, 6, 173];
case 42337: return [42341, -1, 2, 6, 42464];
case 42341: return [42345, -1, 2, 5, 42464];
case 42345: return [42349, 7, 42337];
case 42349: return [42353, -1, 16, 6, 42458];
case 42353: return [42356, 3, 6];
case 42356: return [42358, 0];
} break;
case 87: switch (cp_pc) {
case 42719: return [42723, -1, 224, 0, 42788];
case 42723: return [42725, 0];
case 42725: return [42728, 14, 3];
case 42728: return [42732, -1, 4, 14, 42879];
case 42732: return [42736, -1, 4, 13, 42879];
case 42736: return [42740, 15, 42728];
case 42740: return [42744, 1, 42797];
case 42744: return [42746, 0];
case 42746: return [42749, 6, 190];
case 42749: return [42753, -1, 4, 11, 42849];
case 42753: return [42757, -1, 4, 12, 42849];
case 42757: return [42761, 7, 42749];
case 42761: return [42769, 4, 88, 0, 0, 0];
case 42769: return [42777, 4, 88, 0, 0, 1];
case 42777: return [42780, 6, 190];
case 42780: return [42784, -1, 224, 15, 42849];
case 42784: return [42788, 7, 42780];
} break;
case 88: switch (cp_pc) {
case 42894: return [42898, -1, 224, 0, 42906];
case 42898: return [42900, 0];
case 42900: return [42904, -1, 224, 15, 42849];
case 42904: return [42906, 0];
} break;
} return []; }
