"""Generate GPZ foundation resources from reviewed Research main and the local ROM.

Research is read-only. No coordinates or collision profiles are authored here.
Usage: python generate_gpz_foundation.py --research PATH --rom PATH
"""
import argparse
import copy
import hashlib
import json
from pathlib import Path
import sys
import uuid
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
COMMIT = 'bbcef38a4463b4054d5dbeeede197d9c7b1b8238'
def dump(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2) + '\n', encoding='utf-8')
def sha(raw): return hashlib.sha256(raw).hexdigest()
def guid(value): return str(uuid.uuid5(uuid.NAMESPACE_URL, 'sonic-chaos-gpz/' + value))
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--research', type=Path, required=True)
    ap.add_argument('--rom', type=Path, required=True)
    args = ap.parse_args()
    sys.path.insert(0, str(args.research / 'tools'))
    import level_package as L
    import thz1_object_assets as G
    import thz1_object_10_graphics as M
    import thz1_type18_dynamic_graphics as S
    raw = (args.research / 'data/rom-cache/gpz/implementation-manifest.json').read_bytes()
    manifest = json.loads(raw)
    rom = L.load_rom(args.rom)
    assert sha(rom) == manifest['rom_sha256']
    cache = ROOT / 'POC_notes/rom-cache/gpz'
    dump(cache / 'implementation-manifest.json', manifest)
    for dep in manifest['dependencies']:
        value = json.loads((args.research / dep['path']).read_bytes())
        assert sha(json.dumps(value, sort_keys=True, separators=(',', ':')).encode()) == dep['canonical_json_sha256']
        dump(cache / Path(dep['path']).name, value)
    project_path = ROOT / 'SonicChaos_POC.yyp'
    project = json.loads(project_path.read_text())
    assets = []
    def register(kind, name):
        p = f'{kind}/{name}/{name}.yy'
        if not any(r['id']['path'] == p for r in project['resources']):
            project['resources'].append({'id': {'name': name, 'path': p}})
    def sprite(name, images, origin=(0,0)):
        template = json.loads((ROOT / 'sprites/SPR_chaos_platform/SPR_chaos_platform.yy').read_text())
        template['name'] = template['%Name'] = name
        seq = template['sequence']; seq['name'] = seq['%Name'] = name
        template['width'], template['height'] = images[0].size
        template['bbox_left'] = template['bbox_top'] = 0
        template['bbox_right'], template['bbox_bottom'] = images[0].width-1, images[0].height-1
        seq['xorigin'], seq['yorigin'] = origin
        seq['length'] = float(len(images))
        layer = guid(name + '/layer')
        template['layers'][0]['name'] = template['layers'][0]['%Name'] = layer
        base_key = copy.deepcopy(seq['tracks'][0]['keyframes']['Keyframes'][0])
        keys = []; template['frames'] = []
        for i, image in enumerate(images):
            frame = guid(name + '/' + str(i)); dest = ROOT / 'sprites' / name
            (dest / 'layers' / frame).mkdir(parents=True, exist_ok=True)
            image.save(dest / (frame + '.png'))
            image.save(dest / 'layers' / frame / (layer + '.png'))
            template['frames'].append({'$GMSpriteFrame':'v1','%Name':frame,'name':frame,'resourceType':'GMSpriteFrame','resourceVersion':'2.0'})
            key = copy.deepcopy(base_key); key['id'] = guid(name+'/key/'+str(i)); key['Key'] = float(i)
            key['Channels']['0']['Id'] = {'name':frame,'path':f'sprites/{name}/{name}.yy'}; keys.append(key)
            assets.append({'resource':name,'frame':i,'rgba_sha256':sha(image.tobytes())})
        seq['tracks'][0]['keyframes']['Keyframes'] = keys
        dump(ROOT / 'sprites' / name / (name + '.yy'), template); register('sprites',name)
    def gml_function(name, value): return f'function {name}() {{ return {json.dumps(value,separators=(",",":"))}; }}\n'
    text = f'/// GENERATED by POC_notes/generate_gpz_foundation.py; Research main {COMMIT}.\n'
    prizes=manifest['ordinary_sign_prize_tables']
    text += gml_function('chaos_gpz_prize_rows',[[int(v,16) for v in row] for row in prizes['rows_other_table']])
    text += gml_function('chaos_thz_prize_rows',[[int(v,16) for v in row] for row in prizes['rows_thz_table']])
    palettes = manifest['acts']['gpz1']['graphics']['palettes']
    bg = G.palette_rgba(rom, palettes['background']['index'])
    pal = G.palette_rgba(rom, palettes['sprite']['index'])
    all_blocks = {}
    foreground_atlas = Image.new('RGBA',(512,512))
    block_art = {'research_commit':COMMIT,'review_status':'CANONICAL_RESEARCH_MATCH',
                 'pointer_policy':'canonical Research level_package.block_mapping; bank-relative CPU pointer', 'acts':{}}
    for key, act in manifest['acts'].items():
        width = act['descriptor']['layout']['width_cells']
        cells = [v for row in act['layout']['rows'] for v in row]
        count = act['layout']['runtime_written_cells']
        assert sha(bytes(cells[:count])) == act['layout']['runtime_cells_sha256']
        runtime = cells[:count] + [254] * (4096-count)
        text += gml_function(f'SCR_chaos_{key}_tile_ids',runtime)
        text += gml_function(f'SCR_chaos_{key}_start',act['start']['player_anchor'])
        text += gml_function(f'SCR_chaos_{key}_camera',act['start']['camera'])
        text += gml_function(f'SCR_chaos_{key}_map_width',width)
        rings = [[i,r['world_x'],r['world_y'],int(r['block_id'],16),r['layout_cell_index'],(r['quadrant_origin'][0]//16)+(r['quadrant_origin'][1]//16)*2,'terrain'] for i,r in enumerate(act['rings']['terrain'])]
        text += gml_function(f'SCR_chaos_{key}_terrain_rings',rings)
        obj9 = [[r['object_index'],r['world_x'],r['world_y'],int(r['parameter'],16),int(r['rom_offset'],16),r['source_class']] for r in act['rings']['object09']]
        text += gml_function(f'SCR_chaos_{key}_type09',obj9)
        objects = [[r['index'],r['world_x'],r['world_y'],*[int(r[k],16) for k in ('type_id','flags','parameter','aux0','aux1','rom_offset')],r['status']] for r in act['objects']]
        text += gml_function(f'SCR_chaos_{key}_objects',objects)
        # Import both profile planes, including replacement cells absent from layout.
        text += f'function SCR_chaos_{key}_profiles() {{\n'
        for b in act['blocks']:
            for plane,h in enumerate(b['headers']):
                value = [h['flags'],h['modifier'],h['vertical'],h['horizontal']]
                text += f' global.chaosHeaders{plane}[{b["block_id"]}] = {json.dumps(value)};\n'
        text += '}\n'
        vram, loads = L.build_vram(rom,act['descriptor']['art'])
        assert sha(vram) == act['graphics']['vram_sha256'] and loads == act['graphics']['static_vram_loads']
        pixels = L.block_pixel_maps(rom,vram,only=[b['block_id'] for b in act['blocks']],mapping_rom=act['descriptor']['header']['block_mapping_rom'])
        block_art['acts'][key]=[]
        blocks = {}
        for b in act['blocks']:
            mapping=L.block_mapping(rom,act['descriptor']['header']['block_mapping_rom'],b['block_id'])
            p=pixels[b['block_id']]
            assert mapping==b['mapping']
            assert sha(b''.join(v.to_bytes(2,'little')for v in mapping['attributes']))==b['mapping_sha256']
            assert sha(bytes(c for row in p for c in row))==b['decoded_palette_index_sha256']
            image = Image.new('RGBA',(32,32))
            image.putdata([(0,0,0,0) if c == 0 else (pal if c&16 else bg)[c&15] for row in p for c in row])
            block_art['acts'][key].append({'block_id':b['block_id'],'mapping':mapping,
                'mapping_sha256':b['mapping_sha256'],'index_sha256':b['decoded_palette_index_sha256'],
                'rgba_sha256':sha(image.tobytes()),'opaque_pixels':sum(bool(c)for row in p for c in row)})
            blocks[b['block_id']] = image
            all_blocks[b['block_id']] = image
            # SMS mapping priority is independent of collision plane. Retain only
            # nontransparent pixels of priority-marked 8px mapping cells.
            foreground = Image.new('RGBA',(32,32))
            for cell, attribute in enumerate(mapping['attributes']):
                if attribute & 0x1000:
                    x,y=(cell%4)*8,(cell//4)*8
                    foreground.paste(image.crop((x,y,x+8,y+8)),(x,y))
            foreground_atlas.paste(foreground,((b['block_id']%16)*32,(b['block_id']//16)*32))
        full = Image.new('RGBA',tuple(act['dimensions_pixels']))
        for i,b in enumerate(cells[:count]):
            # All terrain ring frames are separately drawn by the ring manager.
            visible = 70 if b == 71 or b in act['rings']['presence_and_replacement_tables']['ring_blocks'] else b
            full.paste(blocks[visible],((i%width)*32,(i//width)*32))
        draws = []
        for n,x in enumerate(range(0,full.width,1024)):
            name = f'SPR_chaos_{key}_terrain_{n}'
            sprite(name,[full.crop((x,0,min(x+1024,full.width),full.height))])
            draws.append(f'draw_sprite({name},0,{x},0);')
        # Replacement $46 can be transparent: draw intact $47 above its replacement
        # base so breaking removes pixels instead of drawing transparency over them.
        draws.append('for (var cp_cell=0; cp_cell<array_length(global.chaosTileIds); cp_cell++) { if (global.chaosTileIds[cp_cell]==71) draw_sprite(SPR_chaos_gpz_block_47,0,(cp_cell mod global.chaosMapWidth)*32,(cp_cell div global.chaosMapWidth)*32); }')
        obj = f'OBJ_chaos_{key}_terrain'; template = json.loads((ROOT/'objects/OBJ_chaos_thz3_terrain/OBJ_chaos_thz3_terrain.yy').read_text())
        template['name'] = template['%Name'] = obj
        dump(ROOT/'objects'/obj/(obj+'.yy'),template)
        (ROOT/'objects'/obj/'Create_0.gml').write_text('depth=100;\nvar cp_foreground=instance_create_depth(0,0,-60,OBJ_chaos_terrain_foreground);\ncp_foreground.chaosTerrainForegroundSprite=SPR_chaos_gpz_foreground;\n')
        (ROOT/'objects'/obj/'Draw_0.gml').write_text('\n'.join(draws)+'\n'); register('objects',obj)
        roomname = f'ROM_chaos_{key}'; room = json.loads((ROOT/'rooms/ROM_chaos_thz3/ROM_chaos_thz3.yy').read_text())
        room['name'] = room['%Name'] = roomname
        room['roomSettings']['Width'],room['roomSettings']['Height'] = act['dimensions_pixels']
        for order in room['instanceCreationOrder']: order['path'] = f'rooms/{roomname}/{roomname}.yy'
        for layer in room['layers']:
            for instance in layer.get('instances',[]):
                if instance['objectId']['name']=='OBJ_chaos_thz3_terrain': instance['objectId']={'name':obj,'path':f'objects/{obj}/{obj}.yy'}
        dump(ROOT/'rooms'/roomname/(roomname+'.yy'),room); register('rooms',roomname)
        if not any(r['roomId']['name']==roomname for r in project['RoomOrderNodes']): project['RoomOrderNodes'].append({'roomId':{'name':roomname,'path':f'rooms/{roomname}/{roomname}.yy'}})
        print(key,count,'cells',len(rings),'terrain rings',len(obj9),'object rings')
    for b in (70,71,157): sprite(f'SPR_chaos_gpz_block_{b:02x}',[all_blocks[b]])
    sprite('SPR_chaos_gpz_foreground',[foreground_atlas])
    name='OBJ_chaos_terrain_foreground'
    template=json.loads((ROOT/'objects/OBJ_chaos_thz3_terrain/OBJ_chaos_thz3_terrain.yy').read_text())
    template['name']=template['%Name']=name
    dump(ROOT/'objects'/name/(name+'.yy'),template);register('objects',name)
    # Shared object mappings rendered with the GPZ VRAM load and sprite palette.
    for t,base,frames,name,origin in [(0x28,0x6A,[1],'SPR_chaos_gpz_platform',(16,0)),(9,0,[1,2,3,4,5,6],'SPR_chaos_gpz_ring',(8,15))]:
        mapping=G.object_mapping(rom,t); images=[]
        for f in frames:
            cpu=L.u16(rom,mapping['mapping_rom']+f*2)
            result=G.render_frame(vram,G.parse_frame_record(rom,cpu),base,scale=1,margin=0,palette=pal)
            w,h,rgba,_=result; image=Image.frombytes('RGBA',(w,h),rgba)
            if t == 9:
                canvas=Image.new('RGBA',(16,16));canvas.alpha_composite(image,((16-w)//2,16-h));image=canvas
            images.append(image)
        sprite(name,images,origin)
    # Ordinary terrain rings are animated VRAM tiles, not type-$09 mappings.
    # Existing LoadRingArtPointers descriptor $2B00: bank $1D source $855D,
    # VRAM destination $2980. $7450A uploads four successive 128-byte frames
    # every eight updates. Render their actual block-$42 upper-left quadrant.
    assert rom[0x2B00:0x2B06] == bytes.fromhex('00805d858029')
    # LoadRingArtPointers at $2A53 selects RingArt[$2A9A + zone*2],
    # then the act descriptor. All three GPZ acts share this upload source.
    assert rom[0x2A53:0x2A5B] == bytes.fromhex('3a97d2876f260011')
    ring_zone=L.u16(rom,L.u16(rom,0x2A5B)+2)
    assert all(L.u16(rom,ring_zone+act*2)==0x2B00 for act in range(3))
    assert rom[0x7450A:0x7450F] == bytes.fromhex('3a2fd1e607')
    ring_images=[]
    for frame in range(4):
        dynamic=bytearray(vram)
        dynamic[0x2980:0x2A00]=rom[0x7455D+frame*128:0x7455D+(frame+1)*128]
        indices=L.block_pixel_maps(rom,dynamic,only=[0x42],mapping_rom=manifest['acts']['gpz1']['descriptor']['header']['block_mapping_rom'])[0x42]
        image=Image.new('RGBA',(16,16))
        image.putdata([(0,0,0,0) if c==0 else (pal if c&16 else bg)[c&15] for row in indices[:16] for c in row[:16]])
        ring_images.append(image)
    sprite('SPR_chaos_gpz_terrain_ring',ring_images,(8,8))
    for t,base,frames,name,canvas,origin in [(0x26,0x72,[1],'SPR_chaos_gpz_spring',(32,32),(16,24)),(0x1B,0,[14],'SPR_chaos_gpz_spike',(32,40),(16,28)),(0x0F,0,[7,8,9],'SPR_chaos_gpz_poof',(16,16),(8,16))]:
        mapping=G.object_mapping(rom,t);images=[]
        for f in frames:
            result=G.render_frame(vram,G.parse_frame_record(rom,L.u16(rom,mapping['mapping_rom']+f*2)),base,scale=1,margin=0,palette=pal)
            w,h,rgba,_=result; image=Image.frombytes('RGBA',(w,h),rgba);dest=Image.new('RGBA',canvas)
            if t == 0x26:
                # Accepted GameMaker extension adapter draws the coil separately.
                # Use the decoded cap's upper 16 rows on its existing 32x32 canvas.
                image=image.crop((0,0,w,16));dest.alpha_composite(image,((32-w)//2,16))
            else:
                dest.alpha_composite(image,((canvas[0]-w)//2,(canvas[1]-h)//2))
            images.append(dest)
        sprite(name,images,origin)
    dynamic_sign=bytearray(vram)
    _,entries=S.dynamic_list_for_selector(rom,0x12);S.apply_dynamic_entries(dynamic_sign,rom,entries)
    mapping=G.object_mapping(rom,0x18);images=[]
    for f in range(1,6):
        w,h,rgba,_=G.render_frame(dynamic_sign,G.parse_frame_record(rom,L.u16(rom,mapping['mapping_rom']+f*2)),0,scale=1,margin=4,palette=pal)
        image=Image.frombytes('RGBA',(w,h),rgba);dest=Image.new('RGBA',(32,48));dest.alpha_composite(image,((32-w)//2,48-h));images.append(dest)
    sprite('SPR_chaos_gpz_sign',images,(16,48))
    for selector in (1,2,3,4,6):
        sources=[M.pointer(rom,table,selector) for table in M.PLAYER_TYPES['0x01']]
        dynamic=bytearray(vram)
        for source,(dest,n) in zip(sources,M.DESTINATIONS):
            p=int(source['source_rom'],16);dynamic[dest:dest+n*32]=rom[p:p+n*32]
        images=[];mapping=G.object_mapping(rom,0x10)
        for f in M.MAPPING_FRAMES:
            result=G.render_frame(dynamic,G.parse_frame_record(rom,L.u16(rom,mapping['mapping_rom']+f*2)),0,scale=1,margin=4,palette=pal)
            w,h,rgba,_=result;images.append(Image.frombytes('RGBA',(w,h),rgba))
        sprite(f'SPR_chaos_gpz_monitor_{selector:02x}',images,(16,28))
    name='SCR_chaos_gpz_data';dest=ROOT/'scripts'/name
    template=json.loads((ROOT/'scripts/SCR_chaos_level_thz3_data/SCR_chaos_level_thz3_data.yy').read_text());template['name']=template['%Name']=name
    dump(dest/(name+'.yy'),template);(dest/(name+'.gml')).write_text(text,encoding='utf-8');register('scripts',name)
    dump(project_path,project)
    dump(cache/'generated-assets.json',{'research_commit':COMMIT,'rom_sha256':sha(rom),'assets':assets})
    dump(cache/'decoded-block-art.json',block_art)
    # Identity-packed diagnostic atlas; runtime uses the same decoded blocks in
    # precomposed chunks, so there is no mutable block->atlas lookup at runtime.
    sanity=ROOT/'verification/gpz-art-sanity';sanity.mkdir(exist_ok=True)
    atlas=Image.new('RGBA',(512,512))
    for b,image in all_blocks.items():atlas.paste(image,((b%16)*32,(b//16)*32))
    atlas.save(sanity/'block-atlas.png')
    for b in (1,0x3c,0x47,0x46,0x9d,0x8c,0x90,0x94,0x97,0x10):
        all_blocks[b].save(sanity/f'block-{b:02x}.png')
if __name__=='__main__': main()
