// Generate numeric GameMaker constants from the mirrored Research contract.
// Run after replacing the mirrored JSON from Research main.
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const root = path.resolve(__dirname, '..');
const source = path.join(root, 'POC_notes/rom-cache/thz3/implementation-manifest.json');
const raw = fs.readFileSync(source);
const p = JSON.parse(raw);
const supportRaw = fs.readFileSync(path.join(root, 'POC_notes/rom-cache/thz3-boss-support.json'));
const support = JSON.parse(supportRaw);
const mappingRaw = fs.readFileSync(path.join(root, 'POC_notes/rom-cache/thz3/object-50.json'));
const mapping = JSON.parse(mappingRaw);
const fight = support.part_b.b6_defeat_act_clear.fight;
const puffOffsets = fight.child_offsets_from_boss_anchor.map(v => [v.dx,v.dy]);
const puffLifetimes = fight['child_spans_[first_update_since_state_4,updates_alive_or_null_if_alive_at_end_of_sampling]']['0x34'].map(v => v[1]);
const assert = require('assert').strict;
assert.equal(p.rom_sha256, 'eabc8db59746714262d2f91a921d054823484349099a9fcd04fd6e84a1fee607');
assert.equal(p.boss.states.length, 19);
assert.deepEqual(p.boss.vulnerable_states, [6, 9, 12, 15]);
const placement = p.placements.find(x => x.type === '0x50');
assert(placement, 'canonical type $50 placement');
const val = (s, re, label) => { const m = s.match(re); assert(m, label); return Number(m[1]); };
const anchor = placement.world;
assert.deepEqual(anchor, [1936, 238]);
const arena = p.arena_and_camera;
const lock = arena.arena_measured.final_lock.camera;
const pan = arena.pan;
const trigger = [val(arena.trigger.rule, /< (\d+)/, 'trigger X'), 256];
const contact = p.boss.contact_geometry;
const duration = val(p.defeat_and_clear.state_4_updates.toString(), /(\d+)/, 'state 4');
const mappingFrames = mapping.graphics.frames_by_orientation.per_state;
const mappingBounds = mapping.graphics.frames[1].bounds_unmirrored;
const visibleTop = mapping.graphics.registration.visible_rows_rel_anchor_for_frames_1_2[0];
const drawYOffset = visibleTop - mappingBounds.min_y;
assert.equal(drawYOffset, 18, 'ROM screen registration differs from composed PNG bounds');
assert.equal(mapping.graphics.composed_frame_hashes.frame_1_normal.origin_y, -48);
const mappingRows = mapping.states.map(s => {
  const records = s.script.filter(op => op.op === 'record').map(op => [op.duration, op.frame, op.cpu]);
  assert(records.length, `state ${s.state} has mapping records`);
  const back = s.script.find(op => op.op === 'loops_back');
  const loop = back ? records.findIndex(op => op[2] === back.target) : 0;
  assert(loop >= 0, `state ${s.state} loop target resolves`);
  const expected = mappingFrames[s.state];
  assert(expected, `state ${s.state} orientation is documented`);
  const frames = [...new Set(records.map(op => op[1]))].sort();
  assert.deepEqual(frames, [...expected.frames].sort(), `state ${s.state} records match frame table`);
  return {state:s.state, mirrored:expected.orientation === 'mirrored', loop,
    records:records.map(op => [op[0],op[1]])};
});
assert.equal(mappingRows.length, 19);
const lines = [
  '/// GENERATED by POC_notes/generate_thz3_boss_data.js from Research implementation-manifest.json.',
  `/// Source SHA-256: ${crypto.createHash('sha256').update(raw).digest('hex')}`,
  `/// Support cache SHA-256: ${crypto.createHash('sha256').update(supportRaw).digest('hex')}`,
  `/// Object $50 mapping SHA-256: ${crypto.createHash('sha256').update(mappingRaw).digest('hex')}`,
  `#macro CHAOS_BOSS_WORLD_X ${anchor[0]}`,
  `#macro CHAOS_BOSS_WORLD_Y ${anchor[1]}`,
  `#macro CHAOS_BOSS_CREATE_MIN_OUT ${val(arena.creation.rule, /(\d+) <=/, 'creation min') - 256}`,
  `#macro CHAOS_BOSS_CREATE_MAX_OUT ${val(arena.creation.rule, /<= (\d+)/, 'creation max') - 256}`,
  `#macro CHAOS_BOSS_TRIGGER_X ${trigger[0]}`,
  `#macro CHAOS_BOSS_TRIGGER_Y ${trigger[1]}`,
  `#macro CHAOS_BOSS_CAMERA_X ${lock[0]}`,
  `#macro CHAOS_BOSS_CAMERA_Y ${lock[1]}`,
  `#macro CHAOS_BOSS_PAN_LIMIT_X ${val(pan.target, /\((\d+),(\d+)\)/, 'pan target')}`,
  `#macro CHAOS_BOSS_ARENA_LEFT ${lock[0] + 16}`,
  `#macro CHAOS_BOSS_ARENA_RIGHT ${lock[0] + 247}`,
  `#macro CHAOS_BOSS_PATROL_LEFT ${lock[0] + 56}`,
  `#macro CHAOS_BOSS_PATROL_RIGHT ${lock[0] + 200}`,
  `#macro CHAOS_BOSS_HP ${p.boss.hit_points}`,
  `#macro CHAOS_BOSS_DEFEAT_UPDATES ${duration}`,
  `#macro CHAOS_BOSS_EXT_X ${contact.boss_extents_x_y[0]}`,
  `#macro CHAOS_BOSS_EXT_Y ${contact.boss_extents_x_y[1]}`,
  `#macro CHAOS_BOSS_PLAYER_EXT_X ${contact.player_extents_x_y[0]}`,
  `#macro CHAOS_BOSS_PLAYER_EXT_Y ${contact.player_extents_x_y[1]}`,
  `#macro CHAOS_BOSS_DRAW_Y_OFFSET ${drawYOffset}`,
  '#macro CHAOS_BOSS_CONVERTED -2',
  'function chaos_boss_vulnerable_state(cp_state) { return cp_state == 6 || cp_state == 9 || cp_state == 12 || cp_state == 15; }',
  'function chaos_boss_puff_offsets() { return ' + JSON.stringify(puffOffsets) + '; }',
  'function chaos_boss_puff_lifetimes() { return ' + JSON.stringify(puffLifetimes) + '; }',
  'function chaos_boss_state_ids() { return [' + p.boss.states.map(s => s.state).join(',') + ']; }',
  'function chaos_boss_mapping_data(cp_state) { switch (cp_state) {',
  ...mappingRows.map(row => `case ${row.state}: return {mirrored:${row.mirrored},loop:${row.loop},records:${JSON.stringify(row.records)}};`),
  'default: return {mirrored:false,loop:0,records:[[1,0]]}; } }',
  'function chaos_boss_mapping(cp_state, cp_age) {',
  '    var cp_data=chaos_boss_mapping_data(cp_state);',
  '    var cp_total=0,cp_loop_at=0;',
  '    for (var cp_i=0;cp_i<array_length(cp_data.records);cp_i++) {',
  '        if (cp_i == cp_data.loop) cp_loop_at=cp_total;',
  '        cp_total += cp_data.records[cp_i][0];',
  '    }',
  '    var cp_time=max(0,cp_age);',
  '    if (cp_time >= cp_total) cp_time=cp_loop_at+((cp_time-cp_loop_at) mod (cp_total-cp_loop_at));',
  '    for (var cp_i=0;cp_i<array_length(cp_data.records);cp_i++) {',
  '        if (cp_time < cp_data.records[cp_i][0]) return {frame:cp_data.records[cp_i][1],mirrored:cp_data.mirrored};',
  '        cp_time -= cp_data.records[cp_i][0];',
  '    }',
  '    return {frame:0,mirrored:cp_data.mirrored};',
  '}',
  ''
];
const dest = path.join(root, 'scripts/SCR_chaos_boss_data/SCR_chaos_boss_data.gml');
fs.mkdirSync(path.dirname(dest), {recursive:true});
fs.writeFileSync(dest, lines.join('\n'));
