"""Generate numeric $51/support scripts from approved Research caches; no art edits.

The two callback-installed tails and command-3 terminators are decoded from the
verified local ROM using Research's decoder. ROM bytes are never exported.
"""
import json,sys,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
RESEARCH=ROOT.parent/'sonic-chaos-reference-work'
sys.path.insert(0,str(RESEARCH/'tools'))
import rom as R
import gpz_enemy_approval as A
COMMIT='44e0714d16185f213ab1b73822c67e50546ce3f6'
def dump(p,d):
    p.parent.mkdir(parents=True,exist_ok=True)
    p.write_text(json.dumps(d,indent=2)+'\n')
def main():
    r=R.load(ROOT.parent/'source/Sonic Chaos (Europe).sms')
    cache=ROOT/'POC_notes/rom-cache/gpz'
    for n in ('boss-51-runtime','boss-51-fullgame'):
        shutil.copyfile(RESEARCH/f'data/rom-cache/gpz/{n}.json',cache/f'{n}.json')
    runtime=json.loads((cache/'boss-51-runtime.json').read_text())
    approved=json.loads((cache/'enemy-art-approval.json').read_text())
    data={};tables={}
    for typ,st in [(81,runtime['scripts'])]+[(t,approved['types'][str(t)]['animation']) for t in (52,10,18)]:
        rows={}
        tables[typ]=st['table']['state_script_cpus']
        scripts=[s['script'] for s in st['states']]
        if typ==81:scripts += [A.script(r,30,0x9A90),A.script(r,30,0x9C0F)]
        for script in scripts:
            for v in script:
                if v['op']=='record':rows[v['cpu']]=[v['cpu']+4,-1,v['duration'],v['frame'],v['callback']]
                else:
                    a=v['args'];end=v['cpu']+2+len(a)
                    rows[v['cpu']]=[end,v['command']]+a
                    if v['command']==3:
                        off=st['table']['bank']*16384+end-32768
                        assert r[off:off+2]==bytes([255,0])
                        rows[end]=[end+2,0]
        data[typ]=rows
    text='/// Generated by POC_notes/import_gpz_boss.py; Research '+COMMIT+'.\n'
    text+='function chaos_51_sway() { return '+json.dumps(runtime['sway_table']['offsets'])+'; }\n'
    final=json.loads((cache/'boss-51-fullgame.json').read_text())['rows'][-1]
    text+=f"function chaos_51_destination() {{ return {{zone:{final['zone']},act:{final['act']}}}; }}\n"
    text+='function chaos_51_table(cp_type) { switch (cp_type) {\n'
    for typ,tab in tables.items():text+=f'case {typ}: return '+json.dumps(tab)+';\n'
    text+='} return []; }\nfunction chaos_51_record(cp_type,cp_pc) { switch (cp_type) {\n'
    for typ,rows in data.items():
        text+=f'case {typ}: switch (cp_pc) {{\n'
        for pc,v in sorted(rows.items()):text+=f'case {pc}: return '+json.dumps(v)+';\n'
        text+='} break;\n'
    text+='} return []; }\n'
    for name in ('SCR_chaos_gpz_boss_data','SCR_chaos_gpz_boss'):
        p=ROOT/'scripts'/name;p.mkdir(exist_ok=True)
        if name.endswith('_data'):(p/(name+'.gml')).write_text(text)
        s=json.loads((ROOT/'scripts/SCR_chaos_attack/SCR_chaos_attack.yy').read_text());s['name']=s['%Name']=name;dump(p/(name+'.yy'),s)
    p=ROOT/'objects/OBJ_chaos_object_51';p.mkdir(exist_ok=True)
    s=json.loads((ROOT/'objects/OBJ_chaos_object_25/OBJ_chaos_object_25.yy').read_text())
    s['name']=s['%Name']='OBJ_chaos_object_51';s['spriteId']=None
    s['eventList']=[e for e in s['eventList'] if e['eventType'] in (0,8)]
    dump(p/'OBJ_chaos_object_51.yy',s)
    project=json.loads((ROOT/'SonicChaos_POC.yyp').read_text())
    for kind,names in [('scripts',('SCR_chaos_gpz_boss_data','SCR_chaos_gpz_boss')),('objects',('OBJ_chaos_object_51',))]:
        for name in names:
            rel=f'{kind}/{name}/{name}.yy'
            if not any(v['id']['path']==rel for v in project['resources']):project['resources'].append({'id':{'name':name,'path':rel}})
    dump(ROOT/'SonicChaos_POC.yyp',project)
    dump(cache/'boss-51-import.json',{'research_commit':COMMIT,'rom_sha256':R.SHA256,'art_transformation':'NONE','tails':[0x9A90,0x9C0F],'scripts':len(tables[81]),'scheduler':'19 live slots; dynamic allocator scans slots 7..17; head slot7'})
    print('Verified ROM; generated 21 boss scripts and approved support scripts.')
if __name__=='__main__':main()
